src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>FreelancerId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Freelancer</label>
        <referenceTo>Freelancer__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastActivity__c</fullName>
        <label>LastActivity</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3 to 6 months</fullName>
                </value>
                <value>
                    <fullName>1 to 3 months</fullName>
                </value>
                <value>
                    <fullName>Less than 1 month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmployerId__c</fullName>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FreelancerId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Freelancer</label>
        <referenceTo>Freelancer__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HourlyRate__c</fullName>
        <label>HourlyRate</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>JobId</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Freelancer__c.object
<CustomObject>
    <label>Freelancer</label>
    <nameField>
        <label>Freelancer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freelancers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job__c.object
<CustomObject>
    <description>Job</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3 to 6 months</fullName>
                </value>
                <value>
                    <fullName>1 to 3 months</fullName>
                </value>
                <value>
                    <fullName>Less than 1 month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HourlyRate__c</fullName>
        <label>HourlyRate</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>EmployerId__c</fullName>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FreelancerId__c</fullName>
        <label>Freelancer</label>
        <referenceTo>Freelancer__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3 to 6 months</fullName>
                </value>
                <value>
                    <fullName>1 to 3 months</fullName>
                </value>
                <value>
                    <fullName>Less than 1 month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FreelancerId__c</fullName>
        <label>Freelancer</label>
        <referenceTo>Freelancer__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Сonfirmed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RequestTriggerHandler.cls
/**
 * Created by MAX on 08.12.2021.
 */

public with sharing class RequestTriggerHandler {
    public static void afterInsertMethod(List<Request__c> requests) {
        createNotificationForEmployer(requests);
    }

    public static void afterUpdateMethod(List<Request__c> newList, Map<Id, Request__c> oldMap){
        checkRequestStatus(newList, oldMap);
    }

    public static void checkRequestStatus(List<Request__c> newRequests, Map<Id, Request__c> oldRequestMap){
        List<Request__c> rejectedRequests = new List<Request__c>();
        List<Request__c> confirmedRequests = new List<Request__c>();

        for(Request__c req : newRequests) {
            Request__c oldRequest =  oldRequestMap.get(req.Id);

            if(req.Status__c != oldRequest.Status__c){
                if(req.Status__c == 'Rejected'){
                    rejectedRequests.add(req);
                } else if(req.Status__c == 'Confirmed'){
                    confirmedRequests.add(req);
                }
            }
        }

        createNotificationForFreelancer(rejectedRequests,'Rejected');

        createNotificationForFreelancer(confirmedRequests,'Confirmed');
        createContractAndActivity(confirmedRequests);
    }

    public static void createContractAndActivity(List<Request__c> requests){
        List<Contract__c> contracts = new List<Contract__c>();
        List<Activity__c> activities = new List<Activity__c>();

        for(Request__c req :requests){
            Contract__c contract = new Contract__c();
            contract.Name = 'Contract with ' +  req.FreelancerId__r.Name;
            contract.Duration__c = req.Duration__c;
            contract.FreelancerId__c = req.FreelancerId__c;
            contract.HourlyRate__c = req.Hourly_rate__c;
            contract.JobId__c = req.JobId__c;
            contract.Status__c = 'Frozen';

            Activity__c activity = new Activity__c();
            activity.Name = req.FreelancerId__r.Name + 'Activity';
            activity.FreelancerId__c = req.FreelancerId__c;
            activity.JobId__c = req.JobId__c;
            activity.LastActivity__c = Datetime.now();

            activities.add(activity);
            contracts.add(contract);
        }
        
        insert activities;
        insert contracts;
    }

    public static void createNotificationForFreelancer(List<Request__c> requests, String requestStatus){
        List<Notification__c> notifications = new List<Notification__c>();

        List<Id> requestIds = getIdsFromRequestsList(requests);
        List<Request__c> reQRequests = getRequestsByIds(requestIds);

        for (Request__c req : reQRequests) {
            Notification__c notification = new Notification__c();
            notification.Name = 'Your request was ' + requestStatus;
            notification.Text__c = 'Your request was ' + requestStatus + ' (Job "'+ req.JobId__r.Name +'")';
            notification.FreelancerId__c = req.FreelancerId__c;
            notifications.add(notification);
        }

        insert notifications;
    }

    public static List<Id> getIdsFromRequestsList(List<Request__c> requests) {
        List<Id> requestIds = new List<Id>();

        for (Request__c req : requests) {
            requestIds.add(req.Id);
        }

        return requestIds;
    }

    public static void createNotificationForEmployer(List<Request__c> requests) {
        List<Id> requestIds = getIdsFromRequestsList(requests);

        List<Request__c> reQRequests = getRequestsByIds(requestIds);
        Map<Id, Id> jobIdByRequestId = getJobIdByRequestId(requests);
        Map<Id, Id> employerIdByJobId = getEmployerIdByJobId(jobIdByRequestId.values());
        List<Notification__c> notifications = new List<Notification__c>();

        for (Request__c req : reQRequests) {
            Id jobId = jobIdByRequestId.get(req.Id);
            Id employerId = employerIdByJobId.get(jobId);
            Notification__c notification = new Notification__c();
            notification.Name = 'Request from ' + req.FreelancerId__r.Name;
            notification.Text__c = 'You have new request, Please check Job ' + req.JobId__r.Name;
            notification.EmployerId__c = employerId;
            notifications.add(notification);
        }

        insert notifications;
    }

    public static List<Request__c> getRequestsByIds(List<Id> requestIds) {
        return [
                SELECT Id,
                        FreelancerId__r.Name,
                        JobId__r.Name
                FROM Request__c
                WHERE Id IN :requestIds
        ];
    }

    public static Map<Id, Id> getJobIdByRequestId(List<Request__c> requests) {
        Map<Id, Id> jobIdByRequestId = new Map<Id, Id>();

        for (Request__c req : requests) {
            jobIdByRequestId.put(req.Id, req.JobId__c);
        }

        return jobIdByRequestId;
    }

    public static Map<Id, Id> getEmployerIdByJobId(List<Id> jobIds) {
        List<Job__c> jobs = getJobsWithEmployerId(jobIds);
        Map<Id, Id> employerIdByJobId = new Map<Id, Id>();

        for (Job__c job : jobs) {
            employerIdByJobId.put(job.Id, job.EmployerId__c);
        }

        return employerIdByJobId;
    }

    public static List<Job__c> getJobsWithEmployerId(List<Id> jobIds) {
        List<Job__c> jobs = new List<Job__c>();

        jobs = [
                SELECT Id, EmployerId__c
                FROM Job__c
                WHERE Id IN :jobIds
        ];

        return jobs;
    }

}