src/objects/Employer__c.object
<CustomObject>
    <label>Employer</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Freelancer__c.object
<CustomObject>
    <label>Freelancer</label>
    <nameField>
        <label>Freelancer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freelancers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/History__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Histories</relationshipLabel>
        <relationshipName>Histories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>ActivityType</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChangedText__c</fullName>
        <label>ChangedText</label>
        <length>131068</length>
        <type>LongTextArea</type>
    </fields>
    <label>History</label>
    <nameField>
        <label>History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmployerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FreelancerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Freelancer</label>
        <referenceTo>Freelancer__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageTriggerHandler.cls
/**
 * Created by MAX on 09.12.2021.
 */

public with sharing class MessageTriggerHandler {
    public static void afterInsertMethod(List<Message__c> newMessages) {
        createHistory('Create', new Map<Id, Message__c>() , newMessages);
    }

    public static void afterUpdateMethod(List<Message__c> newList, Map<Id, Message__c> oldMap) {
        createHistory( 'Update', oldMap , newList);
    }

    //TODO сделать кверюдля мессаджей где достану заново эти релейшены для фрилансера и имплойера
    public static void createHistory(String activityType, Map<Id, Message__c> oldMessagesMap, List<Message__c> newMessages) {
        List<History__c> histories = new List<History__c>();
        List<Message__c> messages = getMessagesByIds(oldMessagesMap.keySet());

        if (activityType == 'Create') {

            for(Message__c newMess : messages){
                History__c historyCreate = new History__c();
                historyCreate.ActivityId__c = newMess.ActivityId__c;
                historyCreate.ActivityType__c = 'Create';
                historyCreate.ChangedText__c = newMess.Text__c;
                if(newMess.FreelancerId__c != null){
                    historyCreate.Name = newMess.FreelancerId__r.Name + ' Create Message';
                } else if(newMess.EmployerId__c != null){
                    historyCreate.Name = newMess.EmployerId__r.Name + ' Create Message';
                }
                histories.add(historyCreate);
            }
        } else if (activityType == 'Update') {

            for(Message__c newMess : messages){
                Message__c oldMess = oldMessagesMap.get(newMess.Id);

                if(newMess.Text__c != oldMess.Text__c){
                    History__c historyCreate = new History__c();
                    historyCreate.ActivityId__c = newMess.ActivityId__c;
                    historyCreate.ActivityType__c = 'Update';
                    historyCreate.ChangedText__c = 'From: ' + oldMess.Text__c +  '/\n '  + 'To: ' + newMess.Text__c;
                    if(newMess.FreelancerId__c != null){
                        historyCreate.Name = newMess.FreelancerId__r.Name + ' Update Message';
                    } else if(newMess.EmployerId__c != null){
                        historyCreate.Name = newMess.EmployerId__r.Name + ' Update Message';
                    }
                    histories.add(historyCreate);
                } else {
                    break;
                }
            }
        }

        insert histories;
    }

    public static List<Message__c> getMessagesByIds(Set<Id> messIds) {

        return [
                SELECT Id,
                        Text__c,
                        ActivityId__c,
                        FreelancerId__c,
                        FreelancerId__r.Name,
                        EmployerId__c,
                        EmployerId__r.Name
                FROM Message__c
                WHERE Id IN :messIds
        ];
    }
}